server:
  port: 8080
---
spring:
  application:
    name: rinha-api
  datasource:
    url: jdbc:postgresql://db:5432/rinhadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456789
    hikari:
      read-only: false
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        type: trace
---
logging:
  level:
    root: info
    org.hibernate.SQL: debug