server:
  port: 8080
---
spring:
  application:
    name: rinha-api
  datasource:
    url: jdbc:postgresql://db:5432/rinhadb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456789
    hikari:
      read-only: false
      minimum-idle: 20
      maximum-pool-size: 300
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 600000

  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        type: trace
---
logging:
  level:
    root: info
    org.hibernate.SQL: off